In [1]:
# numpy
import numpy as np

In [6]:
#1차원 배열 생성하기
''' 
* np.array(인자 리스트)

리스트로 넘파이 배열을 만드는 함수
리스트가 충첩된 깊이가 곧 배열의 차원이 됨

- 인자 리스트 : 가장 안쪽의 []가 넘파이 배열에서 가장 마지막 차원
'''
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
#2차우너 배열 생성하기
arr2=np.array([[1,2,3,4],[11,12,13,14]])
arr2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [5]:
#3차원 배열 생성하기
arr3=np.array([[[1,2,3,4],[11,12,13,14]],
              [[21,22,23,24],[31,32,33,34]]])
arr3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [7]:
print(arr.shape)
print(arr2.shape)
print(arr3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [9]:
# 다차원 배열 만들기
## 초기화 함수로 넘파이 배열 생성

z1=np.zeros([4])
o2=np.ones([3,4])
r2=np.random.randn(2,3)

In [10]:
z1

array([0., 0., 0., 0.])

In [11]:
o2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
r2

array([[-1.80394233,  1.83181066, -1.98265071],
       [ 0.18201559,  0.86801311, -0.05542786]])

In [13]:
# 4차원 배열 생성하기
# 오른쪽으로 갈수록 하위 차원
# 4x5
r4=np.random.randn(2,2,4,5).round(3)
r4

array([[[[-0.951,  0.779,  0.084,  0.81 , -1.55 ],
         [ 0.889, -0.433,  0.622,  0.376, -0.527],
         [-0.98 ,  0.046,  0.513, -0.789, -1.466],
         [ 1.538,  0.636,  0.239,  0.071, -0.163]],

        [[-0.18 , -0.522, -0.881,  0.847, -0.379],
         [ 1.006,  0.264, -2.807,  0.75 , -2.053],
         [ 1.545,  0.626,  0.842, -0.342,  1.097],
         [-0.3  ,  0.784, -1.753,  0.339, -1.546]]],


       [[[ 1.229, -0.635,  0.479,  1.447, -0.165],
         [-0.33 , -2.46 , -1.756, -0.365, -0.807],
         [ 1.444,  1.063,  0.036,  0.583, -1.211],
         [ 2.503, -0.763, -1.108,  0.523, -0.623]],

        [[ 0.509, -0.418, -1.463,  0.409, -0.136],
         [ 1.517,  1.204, -1.07 ,  1.023, -0.852],
         [ 0.708, -0.611, -0.1  ,  0.069, -0.593],
         [-0.516, -0.431, -0.527, -1.379,  0.065]]]])

In [14]:
#indexing 과 slicing
# indexing 으로 넘파이 배열의 일부 추출하기
# arr[가져올 번호][가져올 번호]
# 넘파이 배열의 일부를 가져오는 코드
# [] 대괄호 하나 당 하나의 차원으로, 높은 차원부터 접근
r4[1][0]

array([[ 1.229, -0.635,  0.479,  1.447, -0.165],
       [-0.33 , -2.46 , -1.756, -0.365, -0.807],
       [ 1.444,  1.063,  0.036,  0.583, -1.211],
       [ 2.503, -0.763, -1.108,  0.523, -0.623]])

In [15]:
r4[1][0][2]

array([ 1.444,  1.063,  0.036,  0.583, -1.211])

In [16]:
r4[1][0][2][4]

-1.211

In [17]:
r4[1,0,2,4]

-1.211

In [18]:
#slicing 으로 넘파이 배열의 일부 추출하기
# arr[시작: 끝 : 간격]
# 넘파이 배열의 여러개의 원소를 가져오는 코드

In [19]:
r4[1][0][2][0:4:2]

array([1.444, 0.036])

In [20]:
# 배열 간 연산, Broadcasting,Aggregation

In [21]:
# 넘파이 배열 간 사칙연산
arr=np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [22]:
arr+arr

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [23]:
arr-arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
arr*arr

array([[  1,   4,   9,  16],
       [100, 121, 144, 169]])

In [25]:
#Broadcasting 연산(Scalar)
# 다차원 넘파이 배열과 하나의 숫자를 사칙 연산하는 경우,
# 넘파이 배열의 모든 원소에 해당 숫자 사칙 연산이 확장되어 적용됨

In [26]:
arr+20

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [27]:
arr*100

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [28]:
#Aggregation(집계)
# 넘파이 배열에 대해 모든 원소를 집계하는 연산
# 수학 : sum, mean, prod / 최대, 최소 : max,min,argmax,argmin
# axis 인자를 주어, 특정 축으로 집계할 수 있음

In [30]:
# 배열 전체의 덧셈, 평균, 곱셈, 최댓값, 최솟값
arr.sum(),arr.mean(),arr.prod(),arr.max(),arr.min()

(56, 7.0, 411840, 13, 1)

In [31]:
# 배열에서의 최대인 원소의 번호, 최소인 원소의 번호
arr.argmax(),arr[1].argmax(),arr.argmin()

(7, 3, 0)

In [33]:
# 특정 축(차원)으로 덧셈 수행하기
arr.sum(axis=0), arr.sum(axis=1)

(array([11, 13, 15, 17]), array([10, 46]))

In [34]:
#응용
arr[1].min(), arr[1][2:].sum()

(10, 25)

In [39]:
# 고급 Broadcasting

arr1=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2=np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])

arr1.shape, arr2.shape

((4, 3), (4, 3))

In [40]:
arr1+arr2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [41]:
arr1+np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [42]:
np.array([[0],[10],[20],[30]])+np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])