# numpy, 배열과 행렬을 다루는 도구

In [1]:
# numpy 임포트
import numpy as np

## numpy 기본 1. 다차원 배열 만들기

In [ ]:
# 1차원 배열 생성하기
넘파이_배열1 = np.array([1,2,3,4])
넘파이_배열1

array([1, 2, 3, 4])

In [ ]:
# 2차원 배열 생성하기
넘파이_배열2 = np.array([[1,2,3,4],[11,12,13,14]])
넘파이_배열2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [ ]:
# 3차원 배열 생성하기
넘파이_배열3 = np.array([ [[1,2,3,4],[11,12,13,14]],
                [[21,22,23,24],[31,32,33,34]] ])
넘파이_배열3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [ ]:
# 배열의 모양 보기
print(넘파이_배열1.shape)
print(넘파이_배열2.shape)
print(넘파이_배열3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [ ]:
z1 = np.zeros([4])    # 0 으로 채운 배열 만들기
o2 = np.ones([3,4])   # 1 로 채운 배열 만들기
r2 = np.random.randn(2,3)   # 랜덤한 숫자 배열 만들기

In [ ]:
z1, o2, r2

(array([0., 0., 0., 0.]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), array([[ 1.40191733, -0.45638921,  0.65412827],
        [ 0.37313099, -0.6024571 ,  1.04497119]]))

In [ ]:
# 배열의 모양 보기
print(z1.shape)
print(o2.shape)
print(r2.shape)

(4,)
(3, 4)
(2, 3)


In [ ]:
# 무척 큰 4차원 배열 생성해보기
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[-0.65 , -2.849,  0.858, -0.571,  0.139],
         [-0.971,  0.039,  1.474,  1.128,  0.602],
         [ 0.028,  0.589, -0.634, -1.564, -0.937],
         [ 1.387,  0.3  ,  0.234, -0.557,  1.662]],

        [[-0.763, -1.209, -0.948, -1.312, -1.073],
         [-0.588, -0.518,  0.89 ,  0.345,  0.017],
         [ 0.754,  0.313, -1.566,  0.371,  0.07 ],
         [-1.037, -1.447,  2.982,  0.042,  1.948]]],


       [[[-1.536, -0.   , -0.863,  2.782,  0.894],
         [ 0.649, -0.011,  1.074,  0.227, -0.499],
         [-0.578, -1.351,  0.514,  0.489, -0.084],
         [-1.246, -0.472,  2.041, -0.244,  0.837]],

        [[ 1.435, -1.16 , -0.58 , -0.927, -0.39 ],
         [-0.758,  0.313,  0.995, -0.919, -1.192],
         [-1.809,  0.902,  1.996,  1.292,  0.354],
         [-0.969,  0.772,  0.754, -1.051,  0.172]]]])

### <연습문제>
1  3  5  7  9  
2  4  6  8  10  
  
형태의 2x5 행렬을 만들어 보세요

## numpy 기본 2. Indexing과 Slicing

In [ ]:
# r4 배열에서, [두번째][첫번째] 접근해서 가져오기
r4[1][0]

array([[-1.536, -0.   , -0.863,  2.782,  0.894],
       [ 0.649, -0.011,  1.074,  0.227, -0.499],
       [-0.578, -1.351,  0.514,  0.489, -0.084],
       [-1.246, -0.472,  2.041, -0.244,  0.837]])

In [ ]:
r4[1][0][2]

array([-0.578, -1.351,  0.514,  0.489, -0.084])

In [ ]:
r4[1][0][2][4]

-0.084

In [ ]:
r4[1,0,2,4]   # 대괄호 대신 쉼표 , 도 차원 접근이 가능

-0.084

In [ ]:
r4[1][0][2][0:4:2]

array([-0.578,  0.514])

In [ ]:
r4[1][0][1:4:2]

array([[ 0.649, -0.011,  1.074,  0.227, -0.499],
       [-1.246, -0.472,  2.041, -0.244,  0.837]])

In [ ]:
# Indexing과 Slicing 같이 적용하기
r4[1][0][1:4:2][1][3:]

array([-0.244,  0.837])

In [ ]:
r4[1,0][1:4:2][1,3:]   # 모두 다 짬뽕!!

array([-0.244,  0.837])

## numpy 기본 3. 배열 간 연산, Broadcasting, Aggregation

In [ ]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [ ]:
arr + arr    # 배열끼리 연산하기 (＋－*/ 모두 가능)

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [ ]:
arr + 20     # 덧셈 브로드캐스팅

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [ ]:
arr * 100    # 곱셈 브로드캐스팅

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [ ]:
# 배열 전체의 덧셈, 평균, 곱셈, 최댓값, 최솟값
arr.sum(), arr.mean(), arr.prod(), arr.max(), arr.min()

(56, 7.0, 411840, 13, 1)

In [ ]:
# 배열에서의 최대인 원소의 번호, 최소인 원소의 번호
arr.argmax(), arr[1].argmax(), arr.argmin()

(7, 3, 0)

In [ ]:
# 특정 축(차원)으로 덧셈 수행하기
arr.sum(axis=0), arr.sum(axis=1)

(array([11, 13, 15, 17]), array([10, 46]))

In [ ]:
# Indexing + Slicing + Aggregation 응용
arr[1].min(), arr[1][2:].sum()

(10, 25)

## numpy 기본 4. 고급 Broadcasting

In [ ]:
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [ ]:
arr1 + arr2          # (4x3)  +  (4x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
arr1 + np.array([0,1,2])     # (4x3) + (1x3)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
#  (4x1) + (1x3)
np.array([[0],[10],[20],[30]]) + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
np.array([0,1,2])

array([0, 1, 2])